config/routes.rb
Rails.application.routes.draw do
  root "snippets#new"
  resources :snippets

  resources :kinds do
    resources :snippets, only: [:create]
  end

end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :snippets, dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :kind
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def index
    @kinds  = Kind.all
    @snippets = Snippet.all
  end
  def show
    @kind  = Kind.find params[:id]
    @snippets = @kind.snippets
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
  end
  def new
  @snippet=Snippet.new
  end
  def show
      @kind  = Kind.find params[:id]
      @snippets = @kind.snippets
    end
  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      redirect_to new_snippet_path(@snippet), notice: "Snippet Created"
    else
      render :new
    end
  end

    private
    def snippet_params
        params.require(:snippet).permit([:title, :work, :kind_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/kinds/index.html.erb
<h1>Snippets</h1>
<p> <% @kinds.each do |kind| %>
  <hr>
<% @count=0 %>
<% @snippets.each do |snippet| %>
<% @count=@count+1 if snippet.kind_id==kind.id %>
<% end %>
<%= link_to "#{kind.name}(#{@count} snippets)" %>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container" >
    <br>
    <baser>

  <div style="height:50px; width:50px; background-color:lightgrey ; border-radius:5px">
  </div>
  <p>Code Snippets</p>
  <hr>

  <%= link_to "Edit Snippets", root_path %>
  |
  <%= link_to "Snippets", kinds_path %>


  <%= yield %>

  <% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

</div>
</body>
</html>

app/views/snippets/index.html.erb
<h1>Snippets Home Page</h1>
<h1>Kind: <%= @kind.name %></h1>
<p>There are <%= @snippets.length %> snippets</p>
<% @snippets.each do |snippet| %>
  <div>
    <%= link_to snippet.title, snippets_path(snippet) %>
  </div>
<% end %>

app/views/snippets/new.html.erb
<h1>Snippets Home Page</h1>

<%= form_for @snippet do |f| %>
<div>
  <%= f.label :kind %>
  <%= f.collection_select :kind_id, Kind.all, :id, :name  %>
</div>
<br>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :work %>
    <%= f.text_area :work %>
  </div>
<br>
  <%= f.submit "Save" %>
<% end %>